### ISSUE TITLE
pytest plugin?

### ISSUE THREAD

**Issue by nicoddemus** [balabit/typesafety#11]
Hi,

Is there interest in a plugin for pytest, similar to the nose plugin? I volunteer to write a PR for it, otherwise I can do it in a separate project.

Cheers,

**Comment by herczy** [comment]
Hi,

I think since a lot of people use pytest, there is. I was already thinking about it, but I don't know about pytest. So if you have the time, please, go ahead with it.

Thanks,
Viktor
